### ISSUE TITLE
Does pulumi-proxmox work directly on the Proxmox host without using the restful endpoint?

### ISSUE THREAD

**Issue by paul-hammant** [ryan4yin/pulumi-proxmox#1]
If you've SSH'd to your proxmox host, you can do proxmox commands from the command line:

```
pct create 123 local:vztmpl/debian-10-standard_10.5-1_amd64.tar.gz --rootfs local-lvm:8 --cores 2 --net0 name=eth0,bridge=vmbr0,ip=dhcp --password 12345 --features nesting=1 --start
```
Then after
```
pct exec 123 -- <some command>
```

Does `pulumi-proxmox` allow access that way instead of via the REST interface from afar? It'd support both of course - an either/or.

**Comment by ryan4yin** [comment]
No, restful endpoint is required.

`pulumi-proxmox` is based on [danitso/terraform-provider-proxmox](https://github.com/danitso/terraform-provider-proxmox), which is implemented on top of proxmox's restful api.

**Comment by ryan4yin** [comment]
since you've SSH'd to the proxmox host, I think you can just set `PROXMOX_VE_ENDPOINT="https://localhost:8006"`.

**Comment by paul-hammant** [comment]
Thanks.
